Open Telemetry and Docker
SURFnet/eduhub-rio-mapper pull request #315
Opened 2024-06-25 11:18 UTC by mdemare

Docker compose setup in which to run api, worker, redis and prometheus.

2024-06-25 11:19 UTC, mdemare commented
`docker-compose up` geeft de volgende error bij mij:

```
api-1         | [otel.javaagent 2024-06-25 11:16:04:750 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 2.2.0
api-1         | #
api-1         | # A fatal error has been detected by the Java Runtime Environment:
api-1         | #
api-1         | #  SIGSEGV (0xb) at pc=0x00007ffffe94ae5e, pid=1, tid=19
api-1         | #
api-1         | # JRE version: OpenJDK Runtime Environment (11.0.14+9) (build 11.0.14+9-post-Debian-1deb11u1)
api-1         | # Java VM: OpenJDK 64-Bit Server VM (11.0.14+9-post-Debian-1deb11u1, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
api-1         | # Problematic frame:
api-1         | # V  [libjvm.so+0x62ae5e]
api-1         | #
api-1         | # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
api-1         | #
api-1         | # An error report file with more information is saved as:
api-1         | # //hs_err_pid1.log
api-1         | #
api-1         | # If you would like to submit a bug report, please visit:
api-1         | #   https://bugs.debian.org/openjdk-11
api-1         | #
api-1         |
api-1         | [error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007fffff61d602]
api-1         |
api-1 exited with code 127
```

2024-10-25 07:25 UTC, joodie requested changes

2024-10-25 07:25 UTC, joodie commented on Dockerfile
> +COPY --from=builder /app/test/test-clients.json /test-clients.json
waarom zit er een test configuratie in de docker image?

2024-10-25 07:25 UTC, joodie commented on project.clj
> +                   ;;:jvm-opts     ["-javaagent:vendor/opentelemetry-javaagent-2.9.0.jar"]
Waarom deze comment?

2024-10-25 07:25 UTC, joodie commented on src/nl/surf/eduhub_rio_mapper/config.clj
> +(defn make-config-and-handlers [web-api?]
Wat doet `web-api?`

2024-10-25 07:25 UTC, joodie commented on src/nl/surf/eduhub_rio_mapper/config.clj
> +                        ;; The web-api doesn't need the job-counter
ik snap dit niet

2024-10-25 07:25 UTC, joodie commented on src/nl/surf/eduhub_rio_mapper/worker.clj
> +            jobs-counter]
documenteer `jobs-counter` in de docstring

2025-01-10 08:55 UTC, joodie approved these changes

2025-04-01 09:18 UTC, merged