Add timestamps to status
SURFnet/eduhub-rio-mapper pull request #328
Opened 2024-08-28 12:43 UTC by mdemare

Add created-at and finished-at timestamps to status.
created-at is set when the job is initially created, finished at is set when the status moves to done, error or timeout.

2024-08-30 07:28 UTC, joodie requested changes

2024-08-30 07:28 UTC, joodie commented on src/nl/surf/eduhub_rio_mapper/endpoints/status.clj
> +                                        (assoc :finished-at (.format datetime-formatter (LocalDateTime/now)))
maak een functie voor die timestamp string

2024-08-30 07:28 UTC, joodie commented on src/nl/surf/eduhub_rio_mapper/endpoints/api.clj
> +(def datetime-formatter (DateTimeFormatter/ofPattern "yyyy-MM-dd HH:mm:ss"))
Voor het verwerken van logs is het denk ik beter om overal UTC te gebruiken ipv "local time". We weten niet welke timezone er op die server ingesteld is en met deze formatting kan je dat ook niet meer terugzien.

De simpelste betrouwbare methode om een ISO-8601 string van UTC timestamp te krijgen is

```
(str (java.time.Instant/now))
```

https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#toString--

2024-09-04 09:46 UTC, mdemare commented
Updated for started-at

2024-09-09 11:38 UTC, joodie approved these changes

2024-09-09 11:39 UTC, merged